/* Mapa do Vale v3: UI real, posição externa, destinos e barreira de pausa. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'analise','movimento-mapa-v3');fs.mkdirSync(dir,{recursive:true});
const out={geradoEm:new Date().toISOString(),passou:false,metodo:'Partida nova pela UI, teclas/cliques reais, posições de entrada e tempo preparados para verificar mapas. Nenhum destino move o jogador.',checagens:[],erros:[],externos:[],capturas:[]};
const check=(nome,ok,evidencia)=>{out.checagens.push({nome,passou:!!ok,evidencia});assert.ok(ok,nome);};
let browser,page;
const snapshot=()=>page.evaluate(()=>FarmWorldMap.snapshot());
const overlap=(a,b)=>a&&b&&Math.max(a.x,b.x)<Math.min(a.x+a.width,b.x+b.width)&&Math.max(a.y,b.y)<Math.min(a.y+a.height,b.y+b.height);
async function refresh(){await page.evaluate(()=>{FarmWorldMap.update(.12);updateBars();snapCamera();render();});}
async function shot(name){await refresh();await page.screenshot({path:path.join(dir,name+'.png')});out.capturas.push(name+'.png');}
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1280,height:800}});out.navegador=browser.version();page.on('pageerror',e=>out.erros.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('farm37_seen_intro','1');window.requestAnimationFrame=()=>0;});
 await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin==='http://127.0.0.1:8766')return r.continue();out.externos.push(u.href);return r.abort();});
 const response=await page.goto('http://127.0.0.1:8766/jogo.html?v=mapa-v3-'+Date.now());out.jogoSHA256=crypto.createHash('sha256').update(await response.body()).digest('hex');
 check('Mapa incluído no build e minimapa oculto no menu',await page.evaluate(()=>!!window.FarmWorldMap&&document.getElementById('worldMapMini').hidden));
 await page.locator('#startMenu .bigBtn').last().click();await page.locator('.cs-option[data-gender="f"]').click();await page.locator('#csName').fill('Lua');await page.locator('#csStartBtn').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>tutorialActive,undefined,{polling:50});
 await page.evaluate(()=>FarmWorldMap.draw());check('Minimapa fica oculto no tutorial',await page.locator('#worldMapMini').isHidden());await page.getByRole('button',{name:'Pular tutorial',exact:true}).click();
 await page.evaluate(()=>{A11Y.noDeath=true;currentWeather=null;weatherCooldown=1e9;histologyMissionQueue.length=0;_lastHistMissionAt=1e9;});await refresh();
 check('Minimapa aparece durante a exploração',await page.locator('#worldMapMini').isVisible());
 const initial=await snapshot();check('Mapa completo tem60×124tiles e13locais reais',initial.world.tilesX===60&&initial.world.tilesY===124&&initial.markers.filter(m=>m.kind==='place').length===13,initial);
 check('Seis NPCs usam posições do mundo atual',initial.markers.filter(m=>m.kind==='npc').length===6&&initial.markers.every(m=>m.x>=0&&m.x<=960&&m.y>=0&&m.y<=1984));
 check('Jogador amarelo tem cor distinta dos NPCs verdes',initial.playerColor!==initial.npcColor&&initial.playerColor==='#ffdc67');
 for(const name of ['Casa','Celeiro','Estufa','Casa das Sementes','Coleta de gelo','Água do oásis'])assert.ok(initial.markers.some(m=>m.name===name),name);
 check('Casa, celeiro, estufa, comunidade, gelo e água constam nas legendas',true);
 const mini=await page.locator('#worldMapMini').boundingBox(),inv=await page.locator('#inv').boundingBox(),status=await page.locator('#status').boundingBox();
 check('Minimapa desktop não cobre inventário ou sinais',!overlap(mini,inv)&&!overlap(mini,status),{mini,inv,status});
 await page.waitForTimeout(5200);await page.evaluate(()=>update(.05));await shot('mapa-minimapa-1280');
 await page.keyboard.press('g');check('G abre o mapa completo com pausa real',await page.evaluate(()=>FarmWorldMap.isOpen()&&readingPanelOpen()&&_actionUiOpen()));
 const before=await page.evaluate(()=>({x:player.x,y:player.y,temp:player.temp,phase:seasonTimer,clock:timeOfDay,npcs:FarmStoryIntegration.navigationState().map(n=>[n.x,n.y]),animals:scenes.main.objects.filter(o=>o.type==='animal').map(a=>({kind:a.kind,x:a.x,y:a.y,animalPhase:a.animalPhase,animalActivity:a.animalActivity,animalClock:a.animalClock}))}));
 await page.keyboard.down('d');await page.evaluate(()=>{update(.25);updateWeather(.25);FarmWorldMap.update(.25);});await page.keyboard.up('d');
 const after=await page.evaluate(()=>({x:player.x,y:player.y,temp:player.temp,phase:seasonTimer,clock:timeOfDay,npcs:FarmStoryIntegration.navigationState().map(n=>[n.x,n.y]),animals:scenes.main.objects.filter(o=>o.type==='animal').map(a=>({kind:a.kind,x:a.x,y:a.y,animalPhase:a.animalPhase,animalActivity:a.animalActivity,animalClock:a.animalClock}))}));
 check('Mapa pausa movimento, clima, relógio, moradores e animais',before.animals.length>0&&before.animals.every(a=>Number.isFinite(a.animalPhase)&&typeof a.animalActivity==='string')&&JSON.stringify(before)===JSON.stringify(after),{before,after});
 check('Foco inicial é Fechar',await page.evaluate(()=>document.activeElement?.textContent==='Fechar · Esc'));
 await page.keyboard.press('Shift+Tab');check('ShiftTab mantém foco no modal',await page.evaluate(()=>document.getElementById('worldMapOverlay').contains(document.activeElement)&&document.activeElement?.dataset?.mapId==='npc:nico'));
 await page.keyboard.press('Tab');check('Tab fecha o ciclo de foco',await page.evaluate(()=>document.activeElement?.textContent==='Fechar · Esc'));
 await page.locator('[data-map-id="place:seed-house"]').click();const marked=await snapshot();
 check('Selecionar local marca destino sem transportar jogador',marked.destination?.name==='Casa das Sementes'&&marked.position.x===before.x&&marked.position.y===before.y,marked.destination);
 check('Destino informa distância e linha reta',await page.locator('.fm-selection').textContent().then(t=>t.includes('passos')&&t.includes('linha reta')));
 await page.locator('.fm-body').evaluate(el=>el.scrollTop=0);
 const whole=await page.locator('#worldMapCanvas').boundingBox(),bodyMap=await page.locator('.fm-body').boundingBox();
 check('Mapa inteiro cabe no painel desktop incluindo extremo sul',whole.y>=bodyMap.y&&whole.y+whole.height<=bodyMap.y+bodyMap.height,{canvas:whole,body:bodyMap});
 await page.locator('.fm-body').evaluate(el=>el.scrollTop=el.scrollHeight);const sticky=await page.locator('#worldMapCanvas').boundingBox();
 check('Mapa permanece visível ao rolar a lista de moradores',sticky.y>=bodyMap.y&&sticky.y+sticky.height<=bodyMap.y+bodyMap.height,{canvas:sticky,body:bodyMap});
 await page.locator('.fm-body').evaluate(el=>el.scrollTop=0);await shot('mapa-completo-1280');
 await page.keyboard.press('g');check('G fecha sem abrir a pausa',await page.evaluate(()=>!FarmWorldMap.isOpen()&&!isPaused));
 await page.locator('#worldMapMini').click();check('Minimapa também abre por clique',await page.evaluate(()=>FarmWorldMap.isOpen()));await page.locator('[data-map-id="npc:lia"]').click();await page.keyboard.press('Escape');
 const old=await snapshot();await page.evaluate(()=>{timeOfDay=13;for(let i=0;i<80;i++)FarmStoryIntegration.update(.05);FarmWorldMap.update(.2);});const moved=await snapshot();
 check('Marcador acompanha morador móvel em vez de coordenada antiga',moved.destination.id==='npc:lia'&&Math.hypot(moved.destination.x-old.destination.x,moved.destination.y-old.destination.y)>5,moved.destination);
 check('ESC restaura foco no botão que abriu',await page.evaluate(()=>document.activeElement?.id==='worldMapMini'));
 await page.locator('#worldMapMini').click();const canvas=await page.locator('#worldMapCanvas').boundingBox();await page.mouse.click(canvas.x+canvas.width*.12,canvas.y+canvas.height*.1);
 check('Clique em chão do mapa cria ponto marcado',(await snapshot()).destination.kind==='point');await page.locator('#worldMapClear').click();check('Limpar marca remove o destino',(await snapshot()).destination===null);
 await page.mouse.click(2,2);check('Clique fora fecha o mapa',!(await snapshot()).open);
 await page.evaluate(()=>{FarmStoryUI.open();FarmWorldMap.draw();});check('Minimapa não compete com outros diálogos',await page.locator('#worldMapMini').isHidden());await page.keyboard.press('Escape');await refresh();
 const indoor=await page.evaluate(()=>{const door=scenes.main.objects.find(o=>o.type==='door_house');player.x=door.x;player.y=door.y+10;player.dir=2;const outside={x:player.x,y:player.y,dir:player.dir};setSceneTo('house');player.x=48;player.y=48;FarmWorldMap.draw();return {outside,map:FarmWorldMap.snapshot()};});
 check('Interior usa posição externa salva, jamais48/48local',indoor.map.inside&&JSON.stringify(indoor.map.position)===JSON.stringify(indoor.outside)&&indoor.map.caption.includes('Dentro de Casa'),indoor);
 await page.keyboard.press('g');await shot('mapa-interior-casa');await page.keyboard.press('Escape');
 const fallback=await page.evaluate(()=>{const old=scenes.main._lastPlayer;delete scenes.main._lastPlayer;FarmWorldMap.draw();const result=FarmWorldMap.snapshot();scenes.main._lastPlayer=old;return result;});
 const door=fallback.markers.find(m=>m.id==='place:house');check('Sem última posição, usa a porta externa como fallback',fallback.position.x===door.x&&fallback.position.y===door.y&&fallback.position.x!==48,fallback.position);
 await page.evaluate(()=>{setSceneTo('main');player.x=264;player.y=920;FarmWorldMap.reset();});await refresh();
 check('Reset elimina a marca e fecha modal',!(await snapshot()).open&&(await snapshot()).destination===null);
 await page.setViewportSize({width:390,height:844});await refresh();
 const smallMini=await page.locator('#worldMapMini').boundingBox(),smallInv=await page.locator('#inv').boundingBox(),top=await page.locator('#topright').boundingBox();
 check('Minimapa390 cabe e não cobre os controles',smallMini.x>=0&&smallMini.x+smallMini.width<=390&&!overlap(smallMini,smallInv)&&!overlap(smallMini,top),{mini:smallMini,inventory:smallInv,top});await shot('mapa-minimapa-390');
 await page.locator('#worldMapMini').click();const card=await page.locator('.fm-card').boundingBox();check('Mapa390 cabe na tela sem transbordar',card.x>=0&&card.y>=0&&card.width<=390&&card.height<=844,card);
 await page.locator('[data-map-id="place:oasis"]').click();await page.locator('.fm-body').evaluate(el=>el.scrollTop=0);await shot('mapa-completo-390');
 check('Locais e moradores continuam acessíveis pelo teclado no celular',await page.locator('.fm-destination').count()===19);await page.keyboard.press('Escape');await refresh();
 check('Nenhum erro JavaScript ou dependência externa',out.erros.length===0&&out.externos.length===0,{errors:out.erros,external:out.externos});out.passou=true;
})().catch(e=>{out.erroFatal=e.stack;process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(dir,'mapa-validacao.json'),JSON.stringify(out,null,2));if(browser)await browser.close();console.log(JSON.stringify({passou:out.passou,checagens:out.checagens.length,erro:out.erroFatal}));});
